- CONTRIBUTING.md
- README.md
Create a basic README.md (adopted from https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) and CONTRIBUTING.md (adopted from Knative GitHub repos) for the master project.
> Basic documentation

- posts/app.py
- posts/requirements.txt
> Connect posts service to db

- events/app.py
- posts/app.py
- posts/test_runner.py
- users/app.py
Clean up style in connect_to_mongodb() so pylint stops complaining and standardize its implementation across events, users, posts.
> Clean up mongo connect pylint style

- .travis.yml
Clean up .travis.yml and possibly fix coveralls reporting 0% coverage.
> Clean up travis (maybe fix coveralls)

- events/app.py
- events/test_events_db.py
Wrote function to respond to request to get all events stored in DB
> Get all events

- posts/app.py
- posts/requirements.txt
- posts/test_post_uploading.py
- users/app.py
Helper function to allow for uploading a post into the posts db along with unit tests.
> Post upload helper

- posts/app.py
Make the posts service serve a fake post at the '/v1/' GET endpoint (get all posts) for testing/demoing.
> Post serve fake data

- posts/app.py
- posts/test_routes.py
- users/app.py
- users/test_routes.py
Untested code is broken code.
Add unit tests for routes in users and posts services and fix a few issues that were noticed because of it.
> (M) Test routes improve coverage

- pageserve/templates/base.html
- posts/test_routes.py
- users/app.py
- users/requirements.txt
- users/test_authentication.py
- users/test_routes.py
- users/test_update_authorization.py
- users/test_user_upsertion.py
Implement back-end authentication handling of Google login in users service.
> (L) Gauth sign in users back end

- events/app.py
- events/test_routes.py
Added tests for the case of an undefined events DB connection to improve coverage.
Also did some minor cleanup of events, also mainly to improve coverage.
> Tests for events DB error and minor cleanup

- .travis.yml
- pageserve/app.py
- pageserve/requirements.txt
- pageserve/test_routes.py
Added test coverage for POST endpoints in pageserve for uploading events and posts.
> Coverage for POST endpoints in pageserve

- posts/app.py
- posts/test_post_uploading.py
Add timestamp to newly uploaded posts using datetime.datetime.now()
> (XS) Posts generate timestamp on upload

- posts/app.py
- posts/test_post_uploading.py
Upload posts timestamps to db as UTC time strings with second accuracy.
> (XS) Posts respresent timestamp as string

- users/app.py
- users/test_routes.py
Add and test route to change authorization level of users from users service
> (M) Users add edit authorization route

- .travis.yml
- events/app.py
Use branch coverage reporting (https://coverage.readthedocs.io/en/v4.5.x/branch.html) and run coverage on all python files (including test files).
> (XS) Better coverage reporting

- events/app.py
- events/eventclass.py
- events/test_events_class.py
- events/test_events_db.py
- events/test_routes.py
- pageserve/app.py
- pageserve/test_serve.py
- users/app.py
Standardize/fix up Apache License headers in important files.
> (M) Standardize Apache 2.0 license use in file headers

- events/app.py
- events/test_routes.py
Added ability to query events by name.
> (S) Query event by name

- CONTRIBUTING.md
- README.md
- events/README.md
- pageserve/README.md
- posts/README.md
- posts/app.py
- users/README.md
Improve master README.md, improve/add each subfolder's README.md.
> (L) Readme overhaul

- pageserve/app.py
- pageserve/templates/index.html
- pageserve/test_serve.py
Better UI - Creates an easier way to assign an event to a post than a text field, displays event IDs and names in a dropdown menu.
> (XS) Event picker for adding posts

- pageserve/static/style.css
- pageserve/templates/base.html
- pageserve/templates/events.html
- pageserve/templates/index.html
Created a navbar to move between pages. Also moved sign/in user buttons to navbar.
Changed font and image sizing app-wide.
> Created navbar and basic style improvements

- pageserve/templates/index.html
#51 had a bug where it tried to access `event.event_id` which didn't exist, breaking our tests. This fixes it to `event._id`
> (XS) Fix event.event_id

- posts/app.py
- posts/test_routes.py
Reorder functions in posts service. Functions grouped into routes, helpers, then config and alphabetized within those groups. Routes alphabetization ordered by endpoint (e.g. "/v1/add"). `test_routes.py` ordered by name of test class.
> (L) Posts reorder functions

- events/app.py
- pageserve/app.py
Fix some linter errors in events and pageserve. Did not get rid of @cmei4444's TODOs.
> (S) Fix up pylint warnings in events pageserve

- pageserve/static/style.css
- pageserve/templates/index.html
Make the UI a little better.
- Center images
- Limit width of images
- Enable nav-bar wrapping on small mobile devices
- Make search bar width a bit more dynamic
https://screenshot.googleplex.com/C1C6NkoCSvn
https://screenshot.googleplex.com/OreGCKDBZxQ
> (S) Better ui

- pageserve/app.py
- pageserve/templates/index.html
- pageserve/test_routes.py
Each post now has a link to the event associated with it, bringing up all of the info about the event.
Created endpoint to handle querying and tests for the endpoint. 
Also made some small fixes to quotes/doctrings in TestSearchEventsRoute test class.
> (M) Created links to events in posts

- pageserve/app.py
- pageserve/templates/index.html
- pageserve/test_routes.py
Make add post pageserve route return error if user is not logged in (previously crashed with a TypeError). Also disables the add post button if the user is not signed in.
> (S) Add post check authentication

- pageserve/static/style.css
- pageserve/templates/base.html
- pageserve/templates/index.html
Most changes were made before demo - just some minor front-end improvements.
- Made navbar stay visible at the top of the screen even when scrolling
- Moved post submit form to top of page for better flow, especially since posts are in reverse order
> (S) Front-end changes

- pageserve/app.py
- pageserve/static/style.css
- pageserve/templates/events.html
- pageserve/templates/index.html
- pageserve/test_routes.py
Created links in each event to all the posts created for that event. Also added some additional logic in the template to tell the user what subset of posts they're looking at.
Also created a dropdown for filtering by event on the home page, but was running into some formatting issues:
Any idea how to right-align this? https://screenshot.googleplex.com/idNBs4wv8g5
Using flexbox to right align causes the content to overlap the dropdown button due to its absolute positioning: https://screenshot.googleplex.com/9LAAfCiBVuU
> Added UI for filtering posts by event

- pageserve/static/style.css
- pageserve/templates/index.html
Add button to clear filter after filtering by event
https://screenshot.googleplex.com/1VYM8XfJhmF
Last PR I promise!
> Add clear filter button

- .travis.yml
- events/Dockerfile
- events/app.py
- events/cloudbuild.yaml
- events/eventclass.py
- events/test_events_class.py
- events/test_events_db.py
- events/test_routes.py
- pageserve/app.py
- pageserve/static/style.css
- pageserve/templates/events.html
- pageserve/templates/index.html
- pageserve/test_routes.py
- pageserve/test_serve.py
Added license comments to files that were missing it, added myself as an author to my files and removed old TODOs.
Some other minor cleanup too.
> Cleanup and documentation
